name: ci
on: [push]
jobs:
  test:
    runs-on: macOS-10.15
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Android SDK
        id: cache-sdk
        uses: actions/cache@v2
        with:
          path: ~/android-sdk
          key: ${{ runner.os }}-android-sdk
      - name: Install Android SDK
        if: steps.cache-sdk.outputs.cache-hit != 'true'
        uses: malinskiy/action-android/install-sdk@release/0.0.6
      - name: Export envvars when using cached install step
        if: steps.cache-sdk.outputs.cache-hit != 'false'
        run: |
          echo "::set-env name=ANDROID_HOME::$HOME/android-sdk"
          echo "::set-env name=ANDROID_SDK_ROOT::$HOME/android-sdk"
          echo "::set-env name=ANDROID_SDK_HOME::$HOME/android-sdk/sdk_home"
      - name: gradle test jacocoTestReport
        run: ./gradlew test jacocoTestReport
      - name: Save test output
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: test-result
          path: build/reports/tests/test
      - name: Save coverage output
        uses: actions/upload-artifact@master
        with:
          name: test-coverage
          path: build/reports/jacoco/test/html
      - name: codecov unit tests
        run: bash <(curl -s https://codecov.io/bash) -f ./build/reports/jacoco/test/jacocoTestReport.xml -F unit
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  integration-test:
    runs-on: macOS-10.15
    strategy:
      matrix:
        api: [21, 22, 23, 24, 25, 26, 27, 28, 29]
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Android SDK
        id: cache-sdk
        uses: actions/cache@v2
        with:
          path: |
            ~/android-sdk
          key: ${{ runner.os }}-android-sdk-${{ matrix.api }}
      - name: Install Android SDK
        if: steps.cache-sdk.outputs.cache-hit != 'true'
        uses: malinskiy/action-android/install-sdk@release/0.0.6
      - name: Export envvars when using cached install step
        if: steps.cache-sdk.outputs.cache-hit != 'false'
        run: |
          echo "::set-env name=ANDROID_HOME::$HOME/android-sdk"
          echo "::set-env name=ANDROID_SDK_ROOT::$HOME/android-sdk"
          echo "::set-env name=ANDROID_SDK_HOME::$HOME/android-sdk/sdk_home"
      - name: integration test
        uses: malinskiy/action-android/emulator-run-cmd@release/0.0.6
        timeout-minutes: 20
        with:
          cmd: ./gradlew integrationTest
          api: ${{ matrix.api }}
          tag: default
          abi: x86
      - name: Generate integration code coverage report
        run: ./gradlew jacocoIntegrationTestReport
      - name: Save integration test output
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: integration-test-result
          path: build/reports/tests/integrationTest
      - name: Save coverage output
        uses: actions/upload-artifact@master
        with:
          name: integration-test-coverage
          path: build/reports/jacoco/jacocoIntegrationTestReport/html
      - name: Save logcat output
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: logcat
          path: artifacts/logcat.log
      - name: codecov integartion tests
        run: bash <(curl -s https://codecov.io/bash) -f ./build/reports/jacoco/jacocoIntegrationTestReport/jacocoIntegrationTestReport.xml -F integration
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
